proxy:
  address: "127.0.0.1:8000"
  token: "advbfsb-adfgsgsg-4435sgs-afgsgdfg"
  basepath: "/neosproxy"

neos:
  url: "http://cms/"
  workspace: "live"
  dimensions:
    - de
    - fr

cache:
  # duration value on which to automatically update the proxy
  autoUpdateDuration: "30m"
  # cache directory
  directory: "/var/data/neosproxy"

observers:
  - name: "foomo-stage"
    type: "foomo"
    url: "https://host.example.com/whatever/to-call"
    verify-tls: true
    token: "1234"
  - name: "foomo-prod"
    type: "foomo"
    url: "https://host.example.com/whatever/to-call"
    verify-tls: true
    token: "1234"
  - name: "slack"
    type: "slack"
    url: "https://hooks.slack.com/services/foo/bar"
    channel: "#dev-ops-test"
  - name: "bla"
    type: "webhook"
    url: "https://host.example.com/whatever/to-call"
    verify-tls: true
    token: "1234"

# observers can subscribe to multiple workspaces
subscriptions:
  - "foomo-prod"
  - "foomo-stage"
  - "slack"
